parameters:
  "service-name":
    default: "Microsoft.Quantum"
  "version-status":
    default: "preview"
  "version":
    default: "2024-02-01-preview"
  "python-sdk-folder":
    default: "{project-root}/azure-sdk-for-python/"
  "java-sdk-folder":
    default: "{project-root}/azure-sdk-for-java/"
  "js-sdk-folder":
    default: "{project-root}/azure-sdk-for-js/"
  "csharp-sdk-folder":
    default: "{project-root}/azure-sdk-for-net/"
  "service-directory-name":
    default: "quantum"
emit: [
  "@azure-tools/typespec-autorest",
  # The Python generator is having a problem emitting Discriminated Types
  # https://microsoft.github.io/typespec/standard-library/discriminated-types
  # "@azure-tools/typespec-python",
]
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    examples-directory: examples
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/quantum.json"
    emitter-output-dir: "{project-root}/../"
  # "@azure-tools/typespec-python":
  #   "package-pprint-name": "\"Azure Quantum\""
  #   "package-mode": "dataplane"
  #   "package-version": 0.0.1
  #   "package-name": "azure-quantum"
  #   "emitter-output-dir": "{python-sdk-folder}/sdk/{service-directory-name}/{package-name}"
